name: Publish to Cocoapods
on:
  push:
    tags:
      - '*'

jobs:
  build:
     runs-on: macOS-13
     steps:
       - uses: actions/checkout@v1
       - name: Publish
         env: 
           COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
         run: pod trunk push YJLoginSDK.podspec
