name: Doc-PR

on:
  pull_request:
    branches:
      - master

jobs:
  generate-document:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v1

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.0.app'

    - name: install-bundler and jazzy
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    - name: Generate document
      run: bundle exec jazzy
