name: Doc-PR

on:
  pull_request:
    branches:
      - master

jobs:
  generate-document:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: install-bundler and jazzy
      run: |
        gem install bundler
        bundle install

    - name: Generate document
      run: bundle exec jazzy

    - name: Archive xcodebuild log
      uses: actions/upload-artifact@v3
      with:
        name: xcodebuild_log
        path: /var/folders/r_/*/*/*.log
